/* Catálogo de FINORA: edita este archivo para cambiar productos, precios y stock. */
const PRODUCTS = [
  {
    "id": 1,
    "name": "Soporte para monitor",
    "category": "Setup",
    "price": 129,
    "stock": 25,
    "image": "img/p1.jpg",
    "description": "Elevador de escritorio en madera y metal negro. Libera espacio debajo del monitor y mejora tu postura. Soporta hasta 30 kg.",
    "badge": "",
    "rating": 4.5,
    "reviews": 24,
    "featured": 1
  },
  {
    "id": 2,
    "name": "Mousepad XL",
    "category": "Setup",
    "price": 79,
    "stock": 40,
    "image": "img/p2.jpg",
    "description": "Superficie de tela suave con base antideslizante. Cubre teclado y mouse. Medidas 90 x 40 cm.",
    "badge": "Nuevo",
    "rating": 5,
    "reviews": 32,
    "featured": 1
  },
  {
    "id": 3,
    "name": "Audífonos inalámbricos",
    "category": "Tecnología",
    "price": 219,
    "stock": 15,
    "image": "img/p3.jpg",
    "description": "Over-ear con cancelación de ruido y hasta 30 horas de batería. Conexión Bluetooth 5.3 y cable de respaldo.",
    "badge": "Nuevo",
    "rating": 4.5,
    "reviews": 18,
    "featured": 1
  },
  {
    "id": 4,
    "name": "Planner financiero",
    "category": "Finanzas",
    "price": 59,
    "stock": 60,
    "image": "img/p4.jpg",
    "description": "Cuaderno tapa dura para planificar ingresos, gastos y metas de ahorro mensuales. 160 páginas.",
    "badge": "",
    "rating": 4.5,
    "reviews": 27,
    "featured": 1
  },
  {
    "id": 5,
    "name": "Lámpara de escritorio LED",
    "category": "Setup",
    "price": 99,
    "stock": 30,
    "image": "img/p5.jpg",
    "description": "Luz cálida regulable en 3 intensidades, brazo articulado y base estable. Ideal para largas jornadas.",
    "badge": "",
    "rating": 4.5,
    "reviews": 15,
    "featured": 1
  },
  {
    "id": 6,
    "name": "Teclado mecánico compacto",
    "category": "Tecnología",
    "price": 249,
    "stock": 12,
    "image": "img/b1.jpg",
    "description": "Formato 75% con switches lineales, retroiluminación y conexión inalámbrica o por cable.",
    "badge": "Nuevo",
    "rating": 4.8,
    "reviews": 9,
    "featured": 0
  },
  {
    "id": 7,
    "name": "Funda para laptop 14\"",
    "category": "Accesorios",
    "price": 89,
    "stock": 35,
    "image": "img/b2.jpg",
    "description": "Funda acolchada repelente al agua con bolsillo frontal para cables y accesorios.",
    "badge": "",
    "rating": 4.4,
    "reviews": 11,
    "featured": 0
  },
  {
    "id": 8,
    "name": "Trading journal",
    "category": "Finanzas",
    "price": 69,
    "stock": 45,
    "image": "img/p4.jpg",
    "description": "Registra tus operaciones, emociones y resultados. Plantillas de análisis semanal incluidas.",
    "badge": "",
    "rating": 4.7,
    "reviews": 14,
    "featured": 0
  },
  {
    "id": 9,
    "name": "Agenda ejecutiva 2026",
    "category": "Trabajo",
    "price": 65,
    "stock": 50,
    "image": "img/p4.jpg",
    "description": "Agenda semanal con vista de objetivos, notas y calendario anual. Papel de 100 g/m².",
    "badge": "",
    "rating": 4.3,
    "reviews": 8,
    "featured": 0
  },
  {
    "id": 10,
    "name": "Cuaderno de estudio",
    "category": "Estudio",
    "price": 39,
    "stock": 80,
    "image": "img/p4.jpg",
    "description": "Cuaderno punteado A5 con índice, numeración de páginas y marcador de cinta.",
    "badge": "",
    "rating": 4.6,
    "reviews": 21,
    "featured": 0
  },
  {
    "id": 11,
    "name": "Organizador de escritorio",
    "category": "Trabajo",
    "price": 74,
    "stock": 28,
    "image": "img/p1.jpg",
    "description": "Módulos en madera para lápices, notas, cargador y celular. Mantén tu escritorio ordenado.",
    "badge": "",
    "rating": 4.5,
    "reviews": 12,
    "featured": 0
  },
  {
    "id": 12,
    "name": "Hub USB-C 7 en 1",
    "category": "Accesorios",
    "price": 119,
    "stock": 20,
    "image": "img/b2.jpg",
    "description": "HDMI 4K, 3 puertos USB-A, lector SD y carga pass-through de 100 W.",
    "badge": "",
    "rating": 4.4,
    "reviews": 16,
    "featured": 0
  }
];
